# Generated by Django 3.2.13 on 2022-06-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_variant_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
