# Generated by Django 3.2.13 on 2022-08-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item_product_variant_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(max_length=77, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
