# Generated by Django 3.2.13 on 2022-10-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220802_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product_id',
        ),
    ]
